// <auto-generated />
namespace NTDShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editpropertyFullName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editpropertyFullName));
        
        string IMigrationMetadata.Id
        {
            get { return "201609260425351_edit-propertyFullName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
